keyChars = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"

puncNames = { ';': "semicolon"
            , ':': "colon"
            , "'": "singleQuote"
            , '"': "doubleQuote"
            , '`': "graveAccent"
            , '~': "tilde"
            , '!': "exclamationMark"
            , '@': "atSign"
            , '#': "octothorpe"
            , '$': "dollarSign"
            , '%': "percentSign"
            , '^': "caret"
            , '&': "ampersand"
            , '*': "asterisk"
            , '(': "lParen"
            , ')': "rParen"
            , '[': "openSquareBracket"
            , ']': "closedSquareBracket"
            , '{': "openCurlyBrace"
            , '}': "closedCurlyBrace"
            , '<': "lessThanSymbol"
            , '>': "greaterThanSymbol"
            , '-': "minusSign"
            , '_': "underscore"
            , '=': "equalsSign"
            , '+': "plusSign"
            , ',': "comma"
            , '.': "period"
            , '\\': "backslash"
            , '/': "forwardSlash"
            , '?': "questionMark"
            , '|': "verticalBar"
            , ' ': "space"
           }

charName = lambda c: puncNames[c] if c in puncNames else c

